<MyLayout>
    FloatLayout:
        size: root.width, root.height


        Label:
            text: 'KiddoVA Alarm App'
            font_size: 25
            size_hint: (0.3, 0.3)
            pos_hint: {'x': 0.34, 'top': 1.1}

        Button:
            text: '+'
            font_size: 32
            size_hint: (0.2, 0.1)
            pos_hint: {'x': 0.70, 'top': 0.15}
            on_press: app.set_alarm()
